### ISSUE TITLE
build fails on ghc 9.0.1

### ISSUE THREAD

**Issue by funketh** [acid-state/acid-state#134]
```hs
[ 5 of 16] Compiling Data.Acid.Abstract
                        
/home/theo/prj/acid-state/src/Data/Acid/Abstract.hs:86:18: error:
    • Couldn't match type: forall event1.
                           (UpdateEvent event1, EventState event1 ~ MethodState event) =>
                           event1 -> IO (MVar (EventResult event1))
                     with: event -> IO (MVar (MethodResult event))
      Expected: AcidState (EventState event)
                -> event -> IO (MVar (EventResult event))
        Actual: AcidState (MethodState event)
                -> forall event1.
                   (UpdateEvent event1, EventState event1 ~ MethodState event) =>
                   event1 -> IO (MVar (EventResult event1))
    • In the expression: _scheduleUpdate
      In an equation for ‘scheduleUpdate’:
          scheduleUpdate = _scheduleUpdate
    • Relevant bindings include
        scheduleUpdate :: AcidState (EventState event)
                          -> event -> IO (MVar (EventResult event))
          (bound at src/Data/Acid/Abstract.hs:86:1)
   |                    
86 | scheduleUpdate = _scheduleUpdate -- Redirection to make Haddock happy.
   |                  ^^^^^^^^^^^^^^^
                        
/home/theo/prj/acid-state/src/Data/Acid/Abstract.hs:113:9: error:
    • Couldn't match type: forall event1.
                           (QueryEvent event1, EventState event1 ~ MethodState event) =>
                           event1 -> IO (EventResult event1)
                     with: event -> IO (MethodResult event)
      Expected: AcidState (EventState event)
                -> event -> IO (EventResult event)
        Actual: AcidState (MethodState event)
                -> forall event1.
                   (QueryEvent event1, EventState event1 ~ MethodState event) =>
                   event1 -> IO (EventResult event1)
    • In the expression: _query
      In an equation for ‘query’: query = _query
    • Relevant bindings include
        query :: AcidState (EventState event)
                 -> event -> IO (EventResult event)
          (bound at src/Data/Acid/Abstract.hs:113:1)
    |                   
113 | query = _query -- Redirection to make Haddock happy.
    |         ^^^^^^    
```
`stack.yaml` used (contains redundant stuff, I just copied the one I use in my actual project):
```yml
packages:
    - .

resolver: nightly-2021-06-21
allow-newer: true

extra-deps:
- compact-0.2.0.0
- data-flags-0.0.3.4
- di-polysemy-0.2.0.0
- flexible-defaults-0.0.3
- hw-mquery-0.2.1.0
- polysemy-RandomFu-0.4.2.1
- random-source-0.3.0.11
- relude-1.0.0.1
- retry-0.8.1.2
- req-3.9.1
- rvar-0.2.0.6
- stm-containers-1.2
- stm-hamt-1.2.0.6
- type-errors-pretty-0.0.1.1
- typerep-map-0.3.3.0

# I always want the most recent version of calamity
- github: simmsb/calamity
  commit: 6bd015851c47aae72b76076e35b2d9cfcd126327
  subdirs: [calamity, calamity-commands]

# Quasi quoter patch for labels
- github: funketh/haskell-src-meta
  commit: fb5c21707a7cc32bc7d4bf4ec00073c3a71b5cfe
  subdirs: [haskell-src-meta]

# GHC 9 patches:
- github: kcsongor/generic-lens
  commit: 8e1fc7dcf444332c474fca17110d4bc554db08c8
  subdirs: [generic-optics, generic-lens, generic-lens-core]
- github: funketh/th-extras
  commit: 57a97b4df128eb7b360e8ab9c5759392de8d1659
- github: metrix-ai/primitive-extras
  commit: 7fc6ae331f70ee23df2d27f4a585560cf50004ac
- github: galenhuntington/fmt
  commit: 913194f8f7aab4445a82994a38c5804a31333b75
- github: polysemy-research/polysemy
  commit: 09c65bdae9c9ce50a55c7ee2ab9681916f09f4c3
  subdirs: [., polysemy-plugin]
- github: funketh/random-fu
  commit: 2d38294582ba211df6a5a2b7f7a2c5e71038b0e7
  subdirs: [random-fu]
- github: polysemy-research/polysemy-zoo
  commit: 1eed0f83f595cb7f666fc238da041080ea284938
```
